services:

    db:
        image: postgres:17
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: dbcore
        volumes:
            - db-data:/var/lib/postgresql/data
            - ../sql:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U root"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    dal:
        build: ../dal
        container_name: dal
        depends_on:
            db:
                condition: service_healthy          # Wait for Postgres to be ready
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: root
            DB_PASS: root
            DB_NAME: dbcore
        ports:
            - "50051:50051"                         # Expose DAL gRPC port
        restart: unless-stopped

volumes:
    db-data:

networks:
    default:
        driver: bridge
